name: Run Ansible Playbook
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key of the target host to known_hosts
      run: |
        mkdir -p ~/.ssh/
        touch  ~/.ssh/known_hosts

        ssh-keyscan -H 65.0.154.214 >> ~/.ssh/known_hosts
      
    - name: Setting up SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
    - name: Run Ansible Playbook
      run: |
        sudo apt update
        sudo apt install -y ansible
        ansible-playbook -i hosts docker.yml --private-key=private_key.pem --user=${{ secrets.ANSIBLE_DEPLOY_USER }}
