name: Workflow 2

on:
  repository_dispatch:
    types: [workflow_2_trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Your Workflow 2 Steps
        # Define steps for Workflow 2 based on your requirements
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: docker.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, SSH private key
          key: ${{ secrets.SSH_KEY }}
          # Optional, literal inventory file contents
          # Optional, SSH known hosts file content

          # Optional, encrypted vault password
          # Optional, additional flags to pass to ansible-playbook
          options: |
             --inventory hosts
             --verbose
