name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.201.114.0 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
      - name: Run Ansible playbook
        run: |
          ansible-playbook -i "13.201.114.0" -u "ubuntu" docker.yml

