name: 'workflow of Child REPO'

on:
  workflow_dispatch:
    branches:
      - main
    

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    environment: prod

    steps:

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      - name: checlout
        uses: actions/checkout@v3
         
      - name: Debug - List Directory Contents
        run: |
          pwd
          ls -la /home/runner/work/ec2configAnsible
          ls -la /home/runner/work/
          ls -la /home/runner/work/ec2configAnsible/ec2configAnsible/docker.yml
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Optional, directory where playbooks live
          directory: ./
          # Required, playbook filepath
          playbook: docker.yml
          
          # Optional, SSH private key
          key: ${{ secrets.SSH_KEY }}
          # Optional, literal inventory file contents
          # Optional, SSH known hosts file content

          # Optional, encrypted vault password
          # Optional, additional flags to pass to ansible-playbook
          options: |
             --inventory hosts
             --verbose
